### ISSUE TITLE
Add any scripts in respective folders of programming languages

### ISSUE THREAD

**Issue by arjuaman** [arjuaman/hacktoberfest2021#1]

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by arjuaman** [comment]
> Please assign me this issue.

Yeah go ahead!

**Comment by saksham117** [comment]
Hi Arju Aman!!
Can I work on this issue?

**Comment by arjuaman** [comment]
Yeah sure @saksham117

**Comment by harshitsuthar77731** [comment]
please assign me

**Comment by arjuaman** [comment]
> please assign me

Done

**Comment by harshitsuthar77731** [comment]
merge my pull request and don't forget to add hactoberfest tag

**Comment by harshitsuthar77731** [comment]
please merge the pr with hactober fest tag

**Comment by himanshukaushal123** [comment]
Please assign me

**Comment by Plk116** [comment]
I want to work on this issue for HacktoberFest 2021. Can I do so?

**Comment by himanshukaushal123** [comment]
please assign me

**Comment by arjunpundir1106** [comment]
can i add menu driven linked list program having all operations if u assign this to me @arjuaman ?

**Comment by arjuaman** [comment]
@all I'm closing all issuees and further additions to this repo as it has been labelled "Excluded" at Hacktoberfest dunno why :( 
I'm thinking of continuing this at https://github.com/arjuaman/Hacktoberfest2k21 as I enjoy promoting beginners and this has been a good medium for start. So you can port your codes there! 🙏
