### ISSUE TITLE
Graphs - All Standard Code and Questions  

### ISSUE THREAD

**Issue by whynesspower** [arjuaman/hacktoberfest2021#30]
Graph Data Structure, All the standard code with explanations in comments, practice questions and a complete package
Please assignmen me this issue

**Comment by arjuaman** [comment]
I'm closing this issue and further additions to this repo as it has been labelled "Excluded" at Hacktoberfest  🙏

**Comment by whynesspower** [comment]
> I'm closing this issue and further additions to this repo as it has been labelled "Excluded" at Hacktoberfest 🙏

What does excluded project mean?

**Comment by arjuaman** [comment]
> > I'm closing this issue and further additions to this repo as it has been labelled "Excluded" at Hacktoberfest 🙏
> 
> What does excluded project mean?

You can check out FAQs on the Hacktoberfest page, there it's listed the conditions.
